version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: nexo_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-nexo_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexo_network

  mailpit:
    image: axllent/mailpit
    container_name: nexo_mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - nexo_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexo_backend
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      DB_HOST: 10.207.39.135 #postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-nexo_db}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-this}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-noreply@localhost}
      RUN_SEEDERS: ${RUN_SEEDERS:-false}
    depends_on:
      - postgres
      - mailpit
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    networks:
      - nexo_network
    command: bun run start:dev

volumes:
  postgres_data:
  mailpit_data:

networks:
  nexo_network:
    driver: bridge

